export const GET_FILM_CAROUSEL = " GET_FILM_CAROUSEL";
export const GET_LIST_FILMS = "GET_LIST_FILMS";
export const SET_FILMS_SAP_CHIEU = "SET_FILMS_SAP_CHIEU";
export const SET_FILMS_DANG_CHIEU = "SET_FILMS_DANG_CHIEU";
